version: '2'
services:
  chrome:
    image: selenium/node-chrome-debug:3.10.0-argon
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
    ports:
      - "5903:5900"
  chrome1:
    image: selenium/node-chrome-debug:3.10.0-argon
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
    ports:
      - "5901:5900"

  chrome2:
    image: selenium/node-chrome-debug:3.10.0-argon
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
    ports:
      - "5902:5900"

  chrome3:
    image: selenium/node-chrome-debug:3.10.0-argon
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
    ports:
      - "5904:5900"

  hub:
    image: selenium/hub:3.10.0-argon
    ports:
      - "4444:4444"
